### ISSUE TITLE
v1beta1 Ingress is deprecated in v1.19+

### ISSUE THREAD

**Issue by chrira** [acend/hugo-training-template#140]
Helm release deploy brings following error:

`W0725 12:39:14.521751    7951 warnings.go:70] networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`

**Comment by phil-pona** [comment]
fixed with: https://github.com/acend/helm-charts/pull/2
